spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  charset:
    console: UTF-8
    file: UTF-8

draw:
  redis:
    address: ${REDIS_ADDRESS}
  payment:
    base-url: ${PAYMENT_BASE_URL}
  metrics:
    refresh-delay-ms: ${DRAW_METRICS_REFRESH_DELAY_MS:5000}
