spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET innodb_lock_wait_timeout=${DB_LOCK_WAIT_TIMEOUT_SECONDS:3}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${SERVER_PORT:8081}

logging:
  charset:
    console: UTF-8
    file: UTF-8
